name: Terraform Destroy (manual)

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: Type 'DESTROY' to confirm
        required: true

permissions:
  id-token: write
  contents: read

env:
  TF_IN_AUTOMATION: "true"
  TF_INPUT: "false"
  AWS_REGION: ${{ secrets.AWS_REGION || 'us-east-1' }}

jobs:
  destroy:
    if: github.event.inputs.confirm == 'DESTROY'
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}
      - name: terraform init
        run: terraform init -upgrade
      - name: terraform destroy
        run: terraform destroy -auto-approve
