name: tf-destroy

on:
  workflow_dispatch:
    inputs:
      aws_region:
        description: "AWS region (e.g., us-east-1)"
        required: true
        default: "us-east-1"
      mode:
        description: "Preview or Destroy"
        required: true
        default: "plan-destroy"
        type: choice
        options: [plan-destroy, destroy]
      confirm_destroy:
        description: "Type DESTROY to proceed (only used when mode=destroy)"
        required: false
        default: ""

permissions:
  id-token: write
  contents: read

env:
  TF_IN_AUTOMATION: "true"

jobs:
  plan_destroy:
    if: ${{ github.event.inputs.mode == 'plan-destroy' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::340752798936:role/jmccoy-github-role
          aws-region: ${{ github.event.inputs.aws_region }}
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5
      - run: terraform init -input=false
      - run: terraform plan -destroy -input=false -no-color

  destroy:
    if: ${{ github.event.inputs.mode == 'destroy' }}
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Guard
        run: |
          if [ "${{ github.event.inputs.confirm_destroy }}" != "DESTROY" ]; then
            echo "You must type DESTROY to proceed."
            exit 1
          fi
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::340752798936:role/jmccoy-github-role
          aws-region: ${{ github.event.inputs.aws_region }}
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5
      - run: terraform init -input=false
      - run: terraform destroy -auto-approve -input=false -no-color
